[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sneep"
authors = [{name = "Dennis Hecker", email = "d.hecker@em.uni-frankfurt.de"}]
dynamic = ["version", "description"]